### ISSUE TITLE
Log just the diff of data alterations, don't log all fields every time

### ISSUE THREAD

**Issue by carlosviol** [jarektkaczyk/revisionable#16]
Is possible to store just the diff of data modifications, maybe with a configurable flag parameter to define if will store the diff or full model data?

Here we have some big text fields that need to be logged, but it's not always altered and other fields that are altered a lot of times every day.

I'm working with PHP + Laravel since 1 month ago, but I can try to help if it's possible!

**Comment by carlosviol** [comment]
And, do you intend to maintain the L4.2 support, or just L5?

Thanks!

**Comment by jarektkaczyk** [comment]
@carlosviol There is no problem with L4, but I haven't been working on this package recently, because personally I don't see the need for any features. It just works the way I want.

Ofc any bugs will be fixed if something comes up.

Feel free create a PR with additional functionality, eg. logging `diff` what you mentioned above. Currently it's not possible and it is intentional - I wanted it to be quick and easyto compare succeeding revisions and it won't be that easy if we store only particular fields. At least in MySQL, obviously still the most popular.

**Comment by carlosviol** [comment]
Cool, I thought and studied better this package with a work partner and we had an idea to resolve this. But your justification for succeeding revisions compare is very important to consider, and maybe we will change our minds about that, and prefer store all fields.

Anyway, thanks!
