### ISSUE TITLE
Trouble with DateTime Object

### ISSUE THREAD

**Issue by shibby** [jarektkaczyk/revisionable#21]
Hello,
when i try to assign datetime object to a DateTime field it gives error.

ErrorException in RevisionableTrait.php line 187: 
Object of class DateTime could not be converted to string

Here is my code
$class = new SomeModel();
$class->some_date = new \DateTime();
$class->save();

some_date field created with schema builder, as dateTime

**Comment by jarektkaczyk** [comment]
@shibby Yep, there's no mutating of `DateTime` specifically, because all the objects are cast to string.

I may change that behaviour, but here are 2 ways of solving this for now:
1. add `some_date` to `dates` in your model, so it will be automatically mutated to appropriate format upon setting 
2. instead of `DateTime` use `Carbon`, which implements `__toString`

**Comment by jarektkaczyk** [comment]
@shibby It's done, you can freely use `DateTime` now.

**Comment by shibby** [comment]
oh man, thanks. i didn't realized your first comment. it gives solution actually. 
btw, thanks again.

**Comment by jarektkaczyk** [comment]
Yeah I gave you 2 options :) But still it was kinda bug, so it's fixed.
